version: '3.4'

  # sqlite
  wiki-service:
    # image: "phreakazoid/mediawiki"  # "kristophjunge/mediawiki"
    build:
      context: onprem/mediawiki
    container_name: wiki-service
    # ports:
    #   - "8080:8080"
    environment:
      - MEDIAWIKI_SERVER=https://gen3.compbio.ohsu.edu
      - MEDIAWIKI_SITENAME=HOPWiki
      - MEDIAWIKI_LANGUAGE_CODE=en
      - MEDIAWIKI_DB_TYPE=sqlite
      - MEDIAWIKI_DB_NAME=wikidb
      - MEDIAWIKI_ENABLE_UPLOADS=1
      - MEDIAWIKI_EXTENSION_VISUAL_EDITOR_ENABLED=0
      - MEDIAWIKI_DEFAULT_SKIN=vector
      - MEDIAWIKI_DEBUG=1
      - MEDIAWIKI_DB_PATH=/data
      - MEDIAWIKI_SECRET_KEY=01777164da1d2797d9af0006e4dacbcd0944cae1647e8678f16f01ee2e77c28b
    volumes:
      - ./onprem/wiki/mediawiki/images:/images
      - ./onprem/wiki/mediawiki/data:/data
      - ./onprem/wiki/mediawiki/resources/assets/healthy-oregon-for-the-web.jpg:/var/www/mediawiki/hop-wiki/resources/assets/healthy-oregon-for-the-web.jpg
      - ./onprem/wiki/mediawiki/LocalSettings.php:/var/www/mediawiki/hop-wiki/LocalSettings.php:ro
      - ./onprem/wiki/mediawiki/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./onprem/wiki/mediawiki/extensions/Auth_remoteuser:/var/www/mediawiki/hop-wiki/extensions/Auth_remoteuser:ro
      # - ./onprem/wiki/mediawiki/log:/var/log/mediawiki  # for debug log
      # - ./onprem/wiki/mediawiki/fastcgi_params:/etc/nginx/fastcgi_params:ro
    networks:
      - devnet

  devproxy-service:
    depends_on:
      - wiki-service        
