# based on:
# 0.10.0 -> 6.8.1
# 1.3.0 -> 7.3.2
FROM amazon/opendistro-for-elasticsearch-kibana:1.10.1
RUN /usr/share/kibana/bin/kibana-plugin install \
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.10.1/enhanced-table-1.10.1_7.9.1.zip
