FROM amazon/opendistro-for-elasticsearch-kibana:1.1.0
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_7.1.1.zip
