# based on:
# 0.10.0 -> 6.8.1
# 1.3.0 -> 7.3.2
FROM amazon/opendistro-for-elasticsearch-kibana:0.10.0
RUN /usr/share/kibana/bin/kibana-plugin install \
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.6.0/enhanced-table-1.6.0_6.8.1.zip
