version: '3'
services:
  esproxy-service:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    container_name: esproxy-service
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - devnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  kibana-service:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    container_name: kibana-service
    environment:
      - SERVER_NAME=kibana-service
      - ELASTICSEARCH_URL=http://esproxy-service:9200
      - SERVER_BASEPATH=/kibana
    ports:
      - 5601:5601
    networks:
      - devnet
    depends_on:
      - esproxy-service

  etl-service:
    image: "gen3-etl-lite:latest"
    container_name: etl-service
    networks:
      - devnet
    volumes:
      - ./apis_configs/sheepdog_creds.json:/gen3_replicator/creds.json
      - ./example-schemas:/schemas_dir
    environment:
      DICTIONARY_URL: https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json
    depends_on:
      - postgres
      - esproxy-service

networks:
  devnet:
