version: '3'
services:
  esproxy-service:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    container_name: esproxy-service
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - devnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  kibana-service:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    container_name: kibana-service
    environment:
      - SERVER_NAME=kibana-service
      - ELASTICSEARCH_URL=http://esproxy-service:9200
      - SERVER_BASEPATH=/kibana
    ports:
      - 5601:5601
    networks:
      - devnet
    depends_on:
      - esproxy-service

  etl-service:
    # image: "gen3-etl-lite:latest"
    build:
      context: gen3_replicator
    container_name: etl-service
    networks:
      - devnet
    volumes:
      - ./Secrets/etl_creds.json:/config/creds.json
      - ./example-schemas:/schemas_dir
    environment:
      DICTIONARY_URL: https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json
    depends_on:
      - postgres
      - esproxy-service
    restart: always


  guppy-service:
    image: "quay.io/cdis/guppy:feat_download-api"
    container_name: guppy-service
    networks:
      - devnet
    depends_on:
      - esproxy-service
    environment:
      - GUPPY_CONFIG_FILEPATH=/guppy/guppy_config.json
      - GEN3_ES_ENDPOINT=http://esproxy-service:9200
      - GEN3_ARBORIST_ENDPOINT=http://arborist-service
    volumes:
      - ./Secrets/guppy_config.json:/guppy/guppy_config.json

networks:
  devnet:
